Part2
tjaskula/PFMCPP_Project3 pull request #2
Opened 2024-04-11 07:35 UTC by tjaskula

Implementation

2024-04-11 16:42 UTC, matkatmusic requested changes

2024-04-11 16:42 UTC, matkatmusic commented on main.cpp
> +// Implementations for Wings, LandingGear, Cabin, and Airplane would follow a similar pattern.
Please implement them.
```
2) provide implementations for the member functions you declared in your 10 user-defined types from the previous video outside of your UDT definitions.
```
- [ ] revise

2024-04-11 17:00 UTC, tjaskula commented on main.cpp
> +// Implementations for Wings, LandingGear, Cabin, and Airplane would follow a similar pattern.
Done

2024-04-13 16:58 UTC, matkatmusic approved these changes

2024-04-13 16:59 UTC, merged